"""empty message

Revision ID: 0e3d30553869
Revises: 461a838e7980
Create Date: 2018-12-04 13:22:31.727294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e3d30553869'
down_revision = '461a838e7980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_disease', 'from_patient')
    op.drop_column('patient_disease', 'message_text')
    op.drop_column('patient_disease', 'date_sent')
    op.add_column('patient_medication', sa.Column('dosage_amount', sa.Float(), nullable=False))
    op.add_column('patient_medication', sa.Column('dosage_instructions', sa.Text(length=500), nullable=False))
    op.add_column('patient_medication', sa.Column('dosage_measure', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_medication', 'dosage_measure')
    op.drop_column('patient_medication', 'dosage_instructions')
    op.drop_column('patient_medication', 'dosage_amount')
    op.add_column('patient_disease', sa.Column('date_sent', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('patient_disease', sa.Column('message_text', mysql.TEXT(), nullable=True))
    op.add_column('patient_disease', sa.Column('from_patient', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
