"""empty message

Revision ID: 461a838e7980
Revises: b92147ccf3ef
Create Date: 2018-12-04 13:14:31.248771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '461a838e7980'
down_revision = 'b92147ccf3ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_disease', sa.Column('date_sent', sa.BigInteger(), nullable=True))
    op.add_column('patient_disease', sa.Column('from_patient', sa.Boolean(), nullable=True))
    op.add_column('patient_disease', sa.Column('message_text', sa.Text(length=500), nullable=True))
    op.drop_column('patient_medication', 'dosage_measure')
    op.drop_column('patient_medication', 'dosage_amount')
    op.drop_column('patient_medication', 'dosage_instructions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_medication', sa.Column('dosage_instructions', mysql.TEXT(), nullable=False))
    op.add_column('patient_medication', sa.Column('dosage_amount', mysql.FLOAT(), nullable=False))
    op.add_column('patient_medication', sa.Column('dosage_measure', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('patient_disease', 'message_text')
    op.drop_column('patient_disease', 'from_patient')
    op.drop_column('patient_disease', 'date_sent')
    # ### end Alembic commands ###
