"""empty message

Revision ID: 8a2c1aeb6dfa
Revises: 
Create Date: 2018-11-20 16:13:23.579234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a2c1aeb6dfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_type',
    sa.Column('unix_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('activity_type', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('unix_timestamp', 'patient_id')
    )
    op.create_table('heart_rate',
    sa.Column('unix_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('heart_rate_measure', sa.Float(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('unix_timestamp', 'patient_id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.Text(length=500), nullable=True),
    sa.Column('date_sent', sa.BigInteger(), nullable=True),
    sa.Column('from_patient', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_medication',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('prescription', sa.Text(length=500), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medication.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('patient_id', 'medication_id')
    )
    op.create_table('steps',
    sa.Column('unix_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('num_steps', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('unix_timestamp', 'patient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activity_type_ibfk_1', 'activity_type', type_='foreignkey')
    op.drop_constraint('heart_rate_ibfk_1', 'heart_rate', type_='foreignkey')
    op.drop_constraint('message_ibfk_1', 'message', type_='foreignkey')
    op.drop_constraint(u'message_ibfk_2', 'message', type_='foreignkey')
    op.drop_constraint(u'patient_ibfk_1', 'patient', type_='foreignkey')
    op.drop_constraint(u'patient_medication_ibfk_1', 'patient_medication', type_='foreignkey')
    op.drop_constraint(u'patient_medication_ibfk_2', 'patient_medication', type_='foreignkey')
    op.drop_constraint(u'steps_ibfk_1', 'steps', type_='foreignkey')

    op.drop_table('steps')
    op.drop_table('patient_medication')
    op.drop_table('message')
    op.drop_table('heart_rate')
    op.drop_table('activity_type')
    op.drop_table('patient')
    op.drop_table('medication')
    op.drop_table('doctor')
    # ### end Alembic commands ###
