"""empty message

Revision ID: b1c71bffa656
Revises: 1abefdf1def5
Create Date: 2018-11-30 23:20:22.871319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1c71bffa656'
down_revision = '1abefdf1def5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_disease',
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('disease_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], )
    )
    op.add_column('patient_medication', sa.Column('dosage_amount', sa.Float(), nullable=False))
    op.add_column('patient_medication', sa.Column('dosage_instructions', sa.Text(length=500), nullable=False))
    op.add_column('patient_medication', sa.Column('dosage_measure', sa.String(length=100), nullable=False))
    op.add_column('patient_medication', sa.Column('notes', sa.Text(length=500), nullable=True))
    op.drop_column('patient_medication', 'prescription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_medication', sa.Column('prescription', mysql.TEXT(), nullable=True))
    op.drop_column('patient_medication', 'notes')
    op.drop_column('patient_medication', 'dosage_measure')
    op.drop_column('patient_medication', 'dosage_instructions')
    op.drop_column('patient_medication', 'dosage_amount')
    op.drop_table('patient_disease')
    # ### end Alembic commands ###
