"""empty message

Revision ID: b92147ccf3ef
Revises: ee79afb33e2a
Create Date: 2018-12-01 18:38:24.916311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects.mysql import BIGINT

# revision identifiers, used by Alembic.
revision = 'b92147ccf3ef'
down_revision = 'c9fa0f03cca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('heart_rate', 'unix_timestamp', existing_type=sa.BigInteger(), type_=BIGINT(unsigned=True))
    op.alter_column('activity_type', 'unix_timestamp', existing_type=sa.BigInteger(), type_=BIGINT(unsigned=True))
    op.alter_column('steps', 'unix_timestamp', existing_type=sa.BigInteger(), type_=BIGINT(unsigned=True))

    # migrate_engine.execute("alter table heart_rate modify unix_timestamp bigint(20) unsigned")
    # migrate_engine.execute("alter table activity_type modify unix_timestamp bigint(20) unsigned")
    # migrate_engine.execute("alter table steps modify unix_timestamp bigint(20) unsigned")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('heart_rate', 'unix_timestamp', type_=sa.BigInteger(), existing_type=BIGINT(unsigned=True))
    op.alter_column('activity_type', 'unix_timestamp', type_=sa.BigInteger(), existing_type=BIGINT(unsigned=True))
    op.alter_column('steps', 'unix_timestamp', type_=sa.BigInteger(), existing_type=BIGINT(unsigned=True))
    # ### end Alembic commands ###
